// This file contains the shared layout from the root component across all children components

"use client"; //This statement is just to make sure createGlobalStyle works from the client side

import "./global.css";
import type { Metadata } from "next";
import { Footer, Nav } from "@/components/sharedLayoutsrafce";
import StyledComponentsRegistry from "../lib/registry";
import { NavProvider } from "@/context/navContextrafce";
import { HomeProvider } from "@/context/homeContextrafce";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <NavProvider>
            <HomeProvider>
              <Nav />
              {children}
              <Footer />
            </HomeProvider>
          </NavProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
