// This file contains the shared layout from the root component across all children components

"use client"; //This statement is just to make sure createGlobalStyle works from the client side

import { GlobalStyle } from "@/stylesrafce";
import type { Metadata } from "next";
import { Footer, Nav } from "@/components/sharedLayoutsrafce";
import StyledComponentsRegistry from "./registry";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <GlobalStyle />
      <html lang="en">
        <body>
          <StyledComponentsRegistry>
            <Nav />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
